services:
  backend:
    image: maven:3.9.4-eclipse-temurin-17
    working_dir: /backend
    command: ./mvnw spring-boot:run
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"

  frontend:
    image: node:20-alpine
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --poll=2000"
    ports:
      - "4200:4200"
    depends_on:
      - backend
